version: '3.8'

services:
  frontend:
    image: vaibhav871/frontend:6195ed1
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
  backend:
    image: vaibhav871/backend:6195ed1
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=backend
      - PORT=5000
      - MONGO_URI=mongodb://mongo_db:27017/sampleApp
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
