version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      APP_NAME: backend
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/sampleApp
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}

